### ISSUE TITLE
Version2.2.0 of virtualhome is not available

### ISSUE THREAD

**Issue by xiaofan-sysu** [xavierpuigf/watch_and_help#13]
Hi~Whether the v2.2.2 of virtualhome is legal for your program?
I tried to find v2.2.0 on the virtualhome site but it is unaccessible now or can you share the executable of v2.2.0 ?
Thanks very much!

**Comment by kswain98** [comment]
Hi! Here are all the execs that are currently available for download: http://virtual-home.org/documentation/master/downloads/downloads.html
