### ISSUE TITLE
which executable to use?

### ISSUE THREAD

**Issue by ishikasingh** [xavierpuigf/watch_and_help#8]
Hi, can you share which linux executable to use exactly, I tried to use a couple of versions (v2.30, v2.2.4, v2.0.1), but I get this error: `'Error processing input graph: Object reference not set to an instance of an object'`.

The link on the README seems to be broken.

I am trying to run `test_single_agent.py` with the given dataset `test_env_set_help.pik`

**Comment by MicroSTM** [comment]
Hi, please use the WAH branch of the VirtualHome repo (https://github.com/xavierpuigf/virtualhome/tree/wah) and v2.2.0
